[package]
name = "cluStaticData"
version = "0.1.2"
authors = ["Denis Kotlyarov (Денис Котляров) <denis2005991@gmail.com>"]
exclude = ["/.travis.yml"]
repository = "https://github.com/clucompany/cluOnceStatic.git"
license = "Apache-2.0"
readme = "README.md"
edition = "2018"

description = ""
keywords = ["once_static_data", "static_data", "cluOnceStatic", "clucompany"]
categories = ["development-tools"]

[dependencies]

